### ISSUE TITLE
Syntax Error upon executing script

### ISSUE THREAD

**Issue by shabbirbashir** [iDefense/ti-export#2]
C:\Users\<my_user_name>\Desktop\TI API>TI-export.py
  File "C:\Users\<my_user_name>\Desktop\TI API\TI-export.py", line 148
    print "Requesting:"
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Requesting:")?

**Comment by krmaxwell** [comment]
Thanks for the report! This appears to be an issue with Python 3 compatibility, which is definitely something we should support.

**Comment by krmaxwell** [comment]
This should have been resolved by bc50c4504e9c33805293c4a19551945c0de37658 - please let me know if it works for you when you get a chance.
